name: Compiler Tests

on: [pull_request]

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xms128m -Xmx4g"

    steps:
      - name: Check out the master branch
        uses: actions/checkout@v4
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 1.11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with gradle
        run: ./gradlew clean compileTestScala --console=plain
      - name: Run tests with timeout
        timeout-minutes: 20
        run: ./gradlew test --console=plain
